
  name: trackwater
  version: 1.0.2
  summary: Track your body water to keep yourself healthy.
  description: |
    This app will track your body water to keep you healthy.
    Each time you drink a glass of water this app will allow
    you to add record of that for you. You just need to set
    target for water drink everyday and it will save it for you.
    It will keep remember your unfinished target even if you
    close the app. So you don't need to keep it running. Just
    use when you drink your water and close. That's it.
    
  grade: stable # must be 'stable' to release into candidate/stable channels
  confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  trackwater:
    command: desktop-launch $SNAP/app
    plugs: [unity7, x11, opengl]

parts:
  app:
    plugin: dump
    source: ./src
    organize:
      main.py: app

    stage-packages:
      - qtdeclarative5-qtquick2-plugin
      - python3-pyqt5
      - python3-pyqt5.qtquick
      - overlay-scrollbar-gtk2
      - libatk-adaptor
      - libcanberra-gtk-module
      - unity-gtk3-module
    after: [desktop-qt5]
